name: lumevents
description: An event management app to search new designs and plan any event.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  persistent_bottom_nav_bar: ^1.5.5
  font_awesome_flutter: ^8.8.1
  liquid_pull_to_refresh: ^2.0.0
  searchable_dropdown: ^1.1.3
  firebase_database: ^3.1.6
  flutter_spinkit: ^4.1.2
  dropdown_banner: ^1.4.0
#  flip_card: ^0.4.4
  getflutter: ^1.0.11
  video_player: ^0.10.11+1
  sqflite: ^1.3.1
  path_provider: ^1.6.11
  fluttertoast: 4.0.1
  flutter_staggered_grid_view: ^0.3.0


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  firebase_storage: ^3.1.6
  image_picker: ^0.6.7+1
  path: ^1.6.4
  email_validator: ^1.0.0
  regexed_validator: ^1.0.4
  flutter_svg:
  mailer2: 1.2.5
  flutter_open_whatsapp: ^0.1.2
  url_launcher: ^5.4.10

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/dreamthyeve.png


  fonts:
    - family: sf_pro
      fonts:
        - asset: fonts/SF-Pro-Rounded-Regular.ttf
    - family: nunito
      fonts:
        - asset: fonts/Nunito-Regular.ttf

