import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'Tiles.dart';
import '../../theme.dart' as Theme;

class CorporateEvents extends StatefulWidget {
  @override
  _CorporateEventsState createState() => _CorporateEventsState();
}

class _CorporateEventsState extends State<CorporateEvents> {
  List<String> imageURLs = [
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F1.%20Cake%20with%20Melting%20Ice%20Cream.jpg?alt=media&token=071dfad3-b9b4-4d04-afa9-e5f418a5ce07',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F2.%20Avengers%20Cake.jpg?alt=media&token=b0958113-a78a-48fe-8766-c9921f8d261e',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F3.%20Elegant%20Cake.jpg?alt=media&token=ab2a2375-fcd1-46d9-958c-2c13d490af4d',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F4.%20Doc%20McStuffin%20Cake.jpg?alt=media&token=8ff9e095-0ffa-4a43-b78c-2a2c86f3f04a',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F5.%20Hedge%20Fences.png?alt=media&token=c70d2ae1-e19b-4f92-880d-24da4b3ad63f',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F6.%20Fire%20Pit.png?alt=media&token=86a1c78b-ad6d-4dac-924f-cce4ed960f2b',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F7.%20Halloween%20Party.png?alt=media&token=627592a3-2e69-4681-b836-bf0b48e42893',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F8.%20Illuminated%20Balloons.png?alt=media&token=8bc68d70-b1fc-4d84-9a25-f946b9f8abbe',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F9.%20Block%20Party.png?alt=media&token=5aca43c7-ec9c-44ac-baec-a2356d81869c',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F10.%20Flower%20Ceiling.jpg?alt=media&token=128e3c9c-f638-4d6c-96ab-21b53f7deda2',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F11.jpg?alt=media&token=5a1afdb2-dc65-4eda-83af-258ee969be5c',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F12.jpg?alt=media&token=e69c9598-c93e-4e5d-b1b7-871ac09ae5ec',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F13.jpg?alt=media&token=8526b33a-c2d4-47a0-8946-45230bef16a8',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F14.jpg?alt=media&token=a7bb130e-bea6-4d65-9ce4-adf93cbfddcd',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F15.jpg?alt=media&token=331a954f-c89c-44df-8f6a-bec88772600e',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F16.jpg?alt=media&token=a5de0996-59be-414f-82c5-a2235e84cdba',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F17.jpg?alt=media&token=7462d789-d7f7-476d-bb24-436576a2ae45',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F18.jpg?alt=media&token=2c775cf2-0460-495e-a2fc-c463c2fd85ef',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F19.jpg?alt=media&token=1bdcf8cf-410f-4f2f-a848-054ddb3421e9',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F20.jpg?alt=media&token=e55c2044-e627-478e-adca-083e7c00b0d4',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F21.jpg?alt=media&token=e483706f-babc-4e48-bf1c-1bcd1861325b',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F22.jpg?alt=media&token=3c298fb7-92b5-4d63-9110-a1aa0099753c',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F23.jpg?alt=media&token=a06a717c-4cab-4c32-9d3e-61660e4d5226',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F24.jpg?alt=media&token=235eab80-8b65-455e-97e3-961ffa99802d',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F25.jpg?alt=media&token=65019e79-6bbd-453f-bd22-0d4eef548b5a',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F26.jpg?alt=media&token=9e895bfa-4859-4d27-b4aa-9063a86c35d6',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F27.jpg?alt=media&token=50ae75ff-8d77-49fb-871b-dd8e65180944',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F28.jpg?alt=media&token=244a8513-9e16-40b1-bd3e-da5d2590c978',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F29.jpg?alt=media&token=da95f239-ef85-4d69-8d7d-4f8533986831',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F30.jpg?alt=media&token=776f00b7-f06a-4544-be4b-5a5187d2636f',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F31.jpg?alt=media&token=b1cfaaf3-65d2-4f4f-97bd-97f0b77af0ea',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F32.jpg?alt=media&token=b5151f21-f530-413a-a6ff-9a0cfa1f9e77',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F33.jpg?alt=media&token=7228f05d-0949-4c52-b9d4-931f01574c73',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F34.jpg?alt=media&token=f8b2b15a-3635-479f-8cc8-fed38a2c1e2c',
    'https://firebasestorage.googleapis.com/v0/b/lumevents-48ff2.appspot.com/o/corporate%20events%2F35.jpg?alt=media&token=fdc29de0-4709-4147-8527-c84a9110d0da'
  ];
  double height, width;
  final scaffoldState = GlobalKey<ScaffoldState>();
  @override
  Widget build(BuildContext context) {
    width = MediaQuery.of(context).size.width;
    height = MediaQuery.of(context).size.height;
    return Scaffold(
      key: scaffoldState,
      appBar: AppBar(
        automaticallyImplyLeading: false,
        backgroundColor: Colors.white,
        title: Container(
          width: double.infinity,
          child: Row(
            children: <Widget>[
              Image.asset(
                'images/dreamthyeve.png',
                scale: 26,
              ),
              Spacer(),
              Text(
                'Inspirations',
                overflow: TextOverflow.fade,
                style: TextStyle(
                    fontSize: 24,
                    fontWeight: FontWeight.bold,
                    color: Theme.MyColors.themeColor,
                    fontFamily: 'nunito'),
                textAlign: TextAlign.left,
              ),
              Spacer()
            ],
          ),
        ),
      ),
      body: ListView(
        children: [
          tiles(
              scaffoldState,
              height,
              width,
              'World Internet Conference',
              imageURLs[0],
              'Many internet giants like Jack Ma attended it They talked about internet sovereignty which attracted people from various companiesInteractive seminars alongside',
              'They had various informative sessions which truly captured people’s attention and addressed the need of the hour which made them trend. This way various people got to showcase and talk about what they believed in. We should try to do the same.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'AYA Global Congress',
              imageURLs[1],
              'The Global Adolescent and Young Adult Cancer Congress is a worldwide premiere event in the field of cancer research. Hundreds of leading healthcare professionals representing industry pioneers and trendsetters from across the globe unite to showcase the latest developments, research and challenges in this rapidly advancing medical field. Among the highlights of the conference was a panel discussion by five young adult cancer survivors about their cancer experience. Every session of the conference was also co-chaired by a young adult cancer survivor and a health-care professional. The project was given to Special Event Company. This Company provided strategic event planning and creative delivery of meetings and events which became the highlight of the event. This event brought a change in the way the services were provided, like planning and development, creative services, onsite logistics, production and A/V, speakers and entertainment, travel and sports and so on. ',
              'By delivering live communications through meetings and events for a diverse clientele will help the company to accomplish this goal. High-level customer service will make the planning experience stress-free and successful. ',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              '“BUY A LADY A DRINK’ CAMPAIGN ',
              imageURLs[2],
              'Stella Artois is not a brand you might typically associate with activism. It’s a company making alcohol & glasses.  However it’s ‘Buy a Lady a Drink’ campaign has been successfully driving awareness of the global water crisis for three years now.Fronted by Matt Damon, it released a TV ad to further encourage consumers to get involved.  For every limited edition bottles purchased, a month of clean water is provided to women and their families in developing countries.   While this initiative is not in any way controversial, it’s still a good example of a brand putting social issues at the heart of its marketing. As well as benefiting a pressing and worthwhile cause, the campaign has also resulted in Stella Artois reaching a younger and more socially-aware audience.  As millennial increasingly look to make a difference in the world, their attention turns to brands that also demonstrate this promise.  As a result, the opportunity to ‘be the generation to help end the global water crisis’ naturally resonated.',
              'This form of marketing is a non-controversial & appealing which take stand on social issues. Targeting the social issues around the globe and also appealing to bring a change for the betterment of society will be very helpful for the company’s growth. One such social issue which company can appeal is dowry in the marriage events. The campaign on the basis of such social issue will show that how company is more concerned about such issue.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              '“MOM ON” CAMPAIGN',
              imageURLs[3],
              'In order to engage a new or forgotten-about audience, yoghurt-brand Yoplait decided to tap into a common public debate: mum-shaming. This relates to the often preachy or patronising information given to mothers about how to be a good parent, and the shaming of those who do not follow it.Its latest campaign, ‘Mom On’, depicts mothers addressing common criticisms they face, such as judgement over breastfeeding, going back to work, and even drinking alcohol. While the ads do not focus on a current event or overly-contentious subject, they are certainly bold in their stance on a specific issue, with the clear potential to offend those who might not agree.This made the campaign hugely memorable, standing out amid a sea of similar and formulaic ads from competitor brands.  For Yoplait, the decision to take on the parenting debate proved worthwhile, ultimately helping the brand to achieve its aim of connecting with a core audience of mothers of all kinds. According to analysis from Google, the ads resulted in a 1,461% increase in brand interest.',
              'This idea is very spicy and attacks the people who judge others and spread negative rumours. Because, the today’s youth is developing and is being more general. The advertisement made to remove such stereotypes can show how modern the company is. This will also increase the clients and our company can also develop as a youth icon.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'India International Yarn Exhibition',
              imageURLs[4],
              'YARNEX is the only exhibition of its kind in the region that brings together under one roof manufacturers and suppliers of fibres, yarns and related services.Emerged as the most important international sourcing platform in India.Comprises of big buyers, international business houses, buying houses & buying agents, apparel brands, composite mills, power loom weavers, knitters, importers, distributors & wholesalers, fashion designers & merchandisers, design studios and institute, trade body representatives and trade media.Showcasing merchandise in India and overseas',
              'The fact that the exhibition is related to same type of people under one roofdiscussing/ making & offering deals/ planning strategies for buying, selling, distributions and production is what makes it interesting. This is a way that helps us to find what we are looking for under one roof only. It seems economical in terms of time, cost and effort. This is a more simplified andunique method. Ensuring such kind of specialisation is required by us as well. We can surely use this as an idea.',
              'CORPORATE SEMINARS'),
          tiles(
              scaffoldState,
              height,
              width,
              'Cybage Run',
              imageURLs[5],
              '“RUN A MILE, EDUCATE A CHILD”, is the slogan so as to celebrate the success stories of underprivileged children. \Constantly providing financial aid to economically backward but promising students so that they can fulfil their educational aspirations.Grants scholarship to students who want to pursue professional coursesStudents get medals and certificate for their amazing performace.',
              'Cybage software Pvt Ltd is therefore very popular because of not justproviding for and achieving economic objectives but also fulfilling social objectives which very enterprise must undertake. So by looking at what the market/ society demands from us, we should provide for these changes or get in touch with experts in such feild to fulfil this responsibility. Therefore, by arranging for online/ offline seminars can prove to be quite useful and attract alot of people/ customers.',
              'CORPORATE SEMINARS'),
          tiles(
              scaffoldState,
              height,
              width,
              '“HEALTHYMAGINATION” CAMPAIGN',
              imageURLs[6],
              'The point of the campaign was to promote global healthcare solutions, especially in developing parts of the world. To help people see the impact of this initiative, GE worked with AGENCYEA to create "movie sets" that represented different healthcare environments where Healthymagination work took place: a rural African clinic, an urban clinic, and an emergency room.The idea was that doctors would share their stories -- live, in front of 700 attendees-- that illustrated how GE\'s healthcare technology played a major role in each setting.In GE\'s case, the point of Healthymagination was to get people talking about a pretty important, but uncomfortable issue: Access to healthcare in impoverished parts of the world.And that can have quite an impact -- this particular campaign, in fact, won a BUSINESS MARKETING ASSOCIATION TOWER AWARD.',
              'Experiential marketing does work for B2B brands. Think about who you\'reselling to, and create an engagement that would not only attract that audience, but also present an opportunity for them to experience your product or service first-hand.This type of campaigns/exhibitions can help our clients to experience our services in real-life. This will give a better interface between the company and our clients.-We can also explain the companies’ strategies to clients in much better way.',
              'CORPORATE ADVERTISEMENTS/ CAMPAIGNS'),
          tiles(
              scaffoldState,
              height,
              width,
              'SMX West 2019',
              imageURLs[7],
              'The project was given to Third Door Media. The highlights of the project were as followsIt covered all aspects of search marketing. Digital marketing being an important aspect of the business world requires the use of SEM and SEO for a successful strategy.It was two days of expert-led, tactic-rich SEO and SEM sessions, more intimate networking, and an opportunity to learn from leading marketing solution providersThe event provided high-quality content at a lower cost and with less time away from the office.',
              'By organising events that tackles the modern age problems and providing quality content at a lower price we can attract marketers from all over the country. Marketers need to stay updated with the changing technology, hence organising events covering topics like digital marketing would lead to the success of our company. Such event also provides networking opportunities with the speakers and attendees.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'TOPO Summit 2018',
              imageURLs[8],
              'The highlights of the project were as follows TOPO Summit 2018 brought together over 1500 sales and marketing leaders responsible for over \$50B in revenue to share the specific best practices, patterns, and plays that drive revenue growth, higher conversion rates, faster sales cycles, and larger average deal sizes.This conference covered sales leadership, sales development, sales operations, account-based selling, marketing, and technology.Speakers like Robert Koehler, Ralph Barsi, Kelvin Glee provided an in-depth knowledge about big companies designing, building, and managing highly scalable sales and marketing organizations.',
              'By focusing on today’s hottest topics that are changing the sales landscape with keynote speakers and in-depth workshops, our company can attract sales and technology professionals from around the world to learn from the best and brightest.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Dreamforce 2018',
              imageURLs[9],
              '	Dreamforce 2018 was one of the largest and most impressive tech events in history, and with around 3,000 sessions decorating the four-day Salesforce conventionOver 1,000 breakout sessions with the opportunity to hear from top global business leaders, as well as get trained and certified.With guest speakers ranging from former American Vice President Al Gore to Andre Iguodala of the NBA’s Golden State Warriors, Salesforce treated the audience to a range of inspirational public figures, entrepreneurs, and thought leaders at its flagship event.',
              'The fact that this event organised a lot of sessions was a dealbreaker itself. It provided learning opportunities to young aspirants. The conference also focussed on other important topics. Speakers like Arianna Huffington and Deepak Chopra spoke to audiences about media, modern life, and mental health. By inviting famous speakers from all over the country and conducting sessions that allow the guests to connect with different people, our company would attract a lot of people',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'International Conference on Marketing and Business Development',
              imageURLs[10],
              'They talked about different strategies and tactics used in the fieldMultiple well-known keynote speakers were invitedDiscussed career and growth in the field',
              'Educational, professional and career related conferences and events garner a huge population especially of those who have just started off. This is what makes the market huge. This audience should be targeted.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              '9th EAI International Conference on Mobile Computing, Applications and Services',
              imageURLs[11],
              'It targeted the growing industry of technologyTalked about innovations and research workHad topics which were very relevant addressed like Artificial Intelligence, Cyber Security, etc.',
              'For conferences and seminar, the ones with relevant and contemporary topics can be chosen and it can contain various topics within like they did at this conference which would increase the number of attendees.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'AFP 2018',
              imageURLs[12],
              'Their invite and brochures had various content headings indirectly telling people what they have in the event for them for example – ‘Who will inspire you?’, ‘What’s your goal?’, etc.Along with the informative concept they had things like ‘Wellness Care Centre’, etc.',
              'Invites can be worked on to make them feel personalised like they did. Along with that, recreational activities can also be held at the event.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              '5th Arts & Humanities Conference',
              imageURLs[13],
              'Various NGOs and big companies were invited to discuss the topics -They had a major overlaying themeThey gave free bus tours to the delegates',
              'Using themes, events can be made more interesting and attractive. This makes people actively engage as well and anticipate the event. We can try creating a similar hype.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Sibos',
              imageURLs[14],
              'It is the world’s annual conference for the financial industry Happens in a prime location Has a theme',
              'Picking a niche and becoming big in it helps the event and the company grow. They also had a prime location like London hence it became even more famous. We can learn from this.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Rodman & Renshaw 2016 Annual Global Investment Conference',
              imageURLs[15],
              'The Rodman & Renshaw 18th Annual Global Investment Conference.More than 300 Public and Private Companies from around the world.Devoted to Biotechnology & Healthcare, Natural Resources, CleanTech, Technology, Media & Telecommunications companies and include corporate presentations. Institutional investors, venture capitalists, private equity firms, and industry executives are welcomed',
              'The Rodman 7 Renshaw conference has invited more companies and investors. Include our company presentations with Q&A sessions. Our company can hold “investors day” to be profiled.An active pursuit of growththrough mergers and acquisition and more investor interest for new products in research and development.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'THE WOOLWORTHS SUMMER SENSORIUM',
              imageURLs[16],
              'Housed within a giant geodesic dome, the immersive multi-sensory food experience provides a rounded paddock-to-plate journey for participants. Consumers can enjoy three summer-inspired dishes taken directly from the pages of Woolworths’ FRESH magazine, each expertly paired with fresh juices.The experience takes full advantage of the dome with visual and immersive 360˚ projections produced by Visual Playground, with full narration to take those inside on a full journey of paddock to the plate.With sessions running daily, the combination of immersive, projection mapping technology with exclusive juice pairings delivered a truly interactive tasting experience.',
              'Our company could apply some unique ideas like these to give the customers a best experience. This type of ideas will bring new clients as well as increase our repurchase rate.These type of events will also show the company’s creativity and ideas to diversify its events.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              '"SUNRISE TO SUNRISE" CAMPAIGN',
              imageURLs[17],
              'The Hyatt Centric explorer vending machine is part of the new “Sunrise to Sunrise” campaign that launched earlier this month, positioning the Hyatt Centric brand as a catalyst for local exploration and discovery. The campaign also includes a collaboration with Passion Passport, a community of travellers, storytellers and creative inspiring exploration and discovery.The machine is filled with a variety of surprises to help travellers explore New York City and beyond, including \$10,000 in Hyatt gift cards, a Vespa motor scooter, a Shinola Detroit Arrow Bicycle, Dry Bar gift cards and more.',
              'The highlights included winning cash prizes, bicycle, gift cards, scooter, cameras, and much more.Our company can also host such things in its events as people like to win the prizes in lucky draws and it will be a better experience for them.Now such events can also be hosted with collaboration with other companies (which are sponsoring the prizes).This will also help to cross promote our brands with other companies and can increase our reach.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'International Conference on Marketing and Business Development',
              imageURLs[18],
              '	They talked about different strategies and tactics used in the fieldMultiple well-known keynote speakers were invitedDiscussed career and growth in the field',
              'Educational, professional and career related conferences and events garner a huge population especially of those who have just started off. This is what makes the market huge. This audience should be targeted',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              '9th EAI International Conference on Mobile Computing, Applications and Services',
              imageURLs[19],
              '	It targeted the growing industry of technologyTalked about innovations and research workHad topics which were very relevant addressed like Artificial Intelligence, Cyber Security, etc.',
              'conferences and seminar, the ones with relevant and contemporary topics can be chosen and it can contain various topics within like they did at this conference which would increase the number of attendees.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'The 2016 PEP Annual Conference',
              imageURLs[20],
              '	Successful gathering of approximately 100 development researchers and practitioners, eminent scholars, representatives of donor/international organizations, and policy actors from more than 30 different countries. Intensive training workshops, the PEP general meeting (where PEP- researchers supported under the PAGE initiative presented their final results) and special high-level policy forum. For all participants PEP present a unique opportunity for global networking, international peer- reviewing and capacity building. The main objective of this event was to produce, collectively, a set of specific recommendations to improve research uptake in policy making.',
              'Event management policy types provide a base policy definition that allows our company to quickly create certain types of polices. Events should utilize a common set of messaging and logging standards. And events should have standard classification schemes and escalation procedures. All recognized events should be captured and recorded.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              '2019 EMEA Conference',
              imageURLs[21],
              '	Between 29 April-1 May, 45 accounting and law member firms from 29 countries will be attending this conference. The conference is taking place in Dubai with support from local UAE accounting firm member Alliott Hadi Shahid. Programme will cover a wide range of topics designed to equip firms with the mindset and insights they need to move together towards a better tomorrow. Session on how and why to invest in the UAE/Gulf region. Block chain technologies, Artificial Intelligence, the importance of creativity in everyday life and how to stay motivated. Alliott Group with not only the alliance’s 40th year but also thanks to the period of significant growth that the group is experiencing. Members will also benefit from a networking programme including dedicated specialist group meeting, exciting cultural tours and local dinners that ensure Dubai is experienced to the full.',
              'The Rodman 7 Renshaw conference has invited more companies and investors. Include our company presentations with Q&A sessions. Our company can hold “investors day” to be profiled.An active pursuit of growththrough mergers and acquisition and more investor interest for new products in research and development.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'TechCrunch Disrupt',
              imageURLs[22],
              'Home to the famous Startup Battlefield competition, TechCrunch Disrupt is an exciting conference for anyone involved in the start-up community. Top-notch speakers like Aileen Lee, Marc Benioff, Marc Andreessen and so on shared their perspectives on the latest technologies, trends and innovations. It conducted Disrupt Battlefield competitionwith \$ 100K in cash and the Disrupt Cup as the winning prize.',
              'By inviting experienced operators giving practical, real-world advice on how to launch, run and grow a successful start-up our company will attract many young entrepreneurs who want to start their own business. Organising competitions make the event more interesting.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Consensus',
              imageURLs[23],
              'Coindesk\'s Consensus is one of the best blockchain and cryptocurrency conferences of the year. The event features over 250 world-class speakers, the hottest startups, media and lots of opportunities to network with more than 8,500 attendees - all in exciting New York City.',
              'Consensus has attracted every major company, developer, founder and investor in the cryptocurrency and blockchain world to engage in an annual discussion about the future of the industry.Since Cryptocurrency is gaining popularity, organising such events would lead to the success of our company',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Dubai Drink Technology Expo 2016',
              imageURLs[24],
              'The best platform for suppliers and manufacturers to broaden their reach and enter the ever-growing Middle East, Africa, Mediterranean and Asian Markets. It plays an important role in the transfer of technology, expertise and innovations in one of the most important industries. It is an added benefit for technology owners, suppliers and manufacturers and to potential investors in the industry as well.',
              'echnology industry is one of the fastest growing industries in today’s world. Organising events which are related to this industry would be advantageous for our company.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Collision Conference',
              imageURLs[25],
              '	Companies like Google, Microsoft, Apple and IBM participated in events throughout the conference, offering valuable networking opportunities for individual attendees and smaller businesses. The conference is known to put a large emphasis on start-ups.',
              'Collision attracts CEOs and founders of some of the fastest growing, most disruptive companies on the planet, while providing ample opportunity to meet potential co-founders, investors or inspiring friends. Inviting famous companies would make our event attractive and inspiring',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Golazzo',
              imageURLs[26],
              'Infopark, Kochi is an Information Technology Park in Kerala, India. They are Infrastructure Service Provider.Biggest Futsal Championship spread across 3 major districts This is a football championship which covers all together 3 major districts in Kochi, India. There are 3 teams as participants in the Golazzo fest After a game of 2 days the winner is declared.',
              'Very healthy approach initiated by Infopark, where participants are encouraged to come forward in teams to play against each other and win. It is very important to warm up and have fun in the middle of work. It is considered to be the best exercise/ practice as it makes the employees more productive also they get to play and freshen up their minds. This is a perfect approach that can be adopted by our company',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'DREAM TWEET',
              imageURLs[27],
              '“Dream Tweet” is an interactive installation that creates a collective dreamscape of a crowd’s dreams and nightmares from the night before. Visitors shared their dreams with our community via Twitter using hash tags. Projection-mapped tweets poured over our “Dream Tweet Bedroom” with unique typefaces. The tweets cascaded the wall and spilled over each other to mimic the free-flowing nature of dreams. The popularity and accessibility of Twitter made it a perfect tool for extracting the crowd’s dreams. The experience was enabled by Twitter aggregator that collected and processed tweets into the installation in real- time.',
              'Projection mapping is the art of making multiple projectors work together on a surface to create amazing visual displays. By playing video, animation or graphics off different shapes and textures, the practice creates a captivating experience of light and movement over previously static objects. Our company can apply such concepts and ideas to increase our social media engagement. As this idea is affordable, emotional appealing and non-controversial, it can be easily implemented in our events and will reflect company’s creativity.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'HBO’S PREMIERE PARTY',
              imageURLs[28],
              ' They created three-dimensional animated projections, including a flying dragon on the exterior of the Roosevelt hotel and a projection wall within a hall of faces photo op installation. There was a backdrop using custom printed wallpaper to cover three of the ballroom’s four walls. Photographer captured guest images in front of the face-lined photo wall.',
              'There is nothing better than relaxing in front of one of your favourite movies. Exposure to pop culture really influences our lives, hobbies and interests, which fundamentally shape the decisions we make. It is a break from the busy world. Our company could try movie themes in its events as people are fond of movies and web shows these days. This is something our company can go for to make our clients excited and we could be on the trending list.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Interaction 16',
              imageURLs[29],
              'The conference brought nearly 1000 design professionals, leaders, students and volunteers together to enjoy three days of workshops and lectures in Helsinki. The overarching theme that Interaction 16 explores is what’s next, in the context of the future of interaction design as a craft, as a profession, and design practice. It included the Education Summit, conference workshops and IxDA Interaction Awards.',
              'Tech companies will learn how to come up with ideas that work and how to make ideas into a reality by taking practical steps. This is ideal for entrepreneurs and businesses that are trying to take a concept and bring it to market. Organising such events would help our company to gain success.',
              'CORPORATE CONFERENCES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Christmas party',
              imageURLs[30],
              '	Key event for the employees of the company and their family members. The festival party was organized at Tulley’s Farm at Crawley Many activities, games and fun fair was there at this event. Occupying a large amount of the venue’s land, all the different elements were tied together with festival flags, festoon lights and plenty of bunting',
              '	This was a funfair organized by the organization for employees and their family members to come together and celebrate the festival. Such an event can increase employee’s dedication and commitment towards the organization and can increase productivity.Their families come together and get to know each other and enjoy the day.REFERENCE LINKS: www.mgnevents.co.uk',
              'CORPORATE PARTIES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Tech Conference After Party',
              imageURLs[31],
              'US tech organisation with global reach, runs events all over the world throughout the year, including a two-day conference for prospects, customers and partners in the procurement sector. The London conference was scheduled in November.',
              'This conference after party was organized for the delegates to enjoy end of the day of the stressful conference and encourage them to return for the meeting next day.This formed the basis of the brief, to deliver an informal event where the guests could enjoy meeting others in a relaxed atmosphere.Atmosphere was the key. The relaxed and chilled feel at the beginning enabled approximately 600 guests to network and chat, before things became more lively and funky later in the evening.',
              'CORPORATE PARTIES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Royal York Hotel 90th Anniversary',
              imageURLs[32],
              'Grand inauguration of the event and along with it they inaugurated some newly constructed parts of their hotel.Floral installation was done keeping in mind the hotel’s legacy and it was mentioned across various articlesThe event showed the hotel as ‘heritage and history’ of the city',
              'We can learn that creative methods of expressing like usage of flowers in a particular manner can make the event trend. Also, when you connect the event or establishment to the heritage then a personal link is created with the people and event automatically becomes more intriguing for them!',
              'CORPORATE PARTIES'),
          tiles(
              scaffoldState,
              height,
              width,
              'The Third Annual Polar Bear Affair',
              imageURLs[33],
              'It is the annual gala of PBI,They raise awareness and funds for polar bears conservation through their galaBig celebrities and companies were invitedThey had various interactive activities and a great range of food as well',
              'They prove that charity can be done while having fun and that is what encourages people even more to attend these events. Their wide range of food is also something which was talked about along with their activities which kept the event engaging and fun. They also had band performances. We can put all this information to use.',
              'CORPORATE PARTIES'),
          tiles(
              scaffoldState,
              height,
              width,
              'Paint a story (150 YrsAnniversay Celebration)',
              imageURLs[34],
              'To do that, LEO Events created a two-story digital “open book” as a stage backdrop. An actor playing co-founder, Henry Sherwin, then stepped out of the book and onto the stage to describe the beginnings of the company.The celebration also included a clock of oversized paint chips, a commissioned custom song called “We’ve Got a Story To Tell,” and virtual painters “painting” the Sherwin-Williams logo on-screen—all that served to engage the audience throughout the nigh',
              '	LEO knew Sherwin-Williams had a story to tell, so that became the motive – to showcase that story in a mega way.Before the 75-minute production even began, interactive walk-in activities and videos engaged the audience for the 90 minutes it took to fill the arena, making them feel like participants and not just spectators.Countdown clocks, fashioned from oversized paint chips, ticked down the final minutes to show time. Some of the most popular services of Leo Event (the event management company) that made it popular for the 150 yrs anniversary event was',
              'CORPORATE PARTIES'),
//          tiles(
//              scaffoldState,
//              height,
//              width,
//              'COMPANY’S RETREAT PARTY',
//              imageURLs[35],
//              '	In the company’s retreat, they made the event more appealing for their employees by including Custom tents, custom signage, board games and participant activities and prizes, smoker’s bar and campfire, live entertainment.The employees had a wonderful experience as it was very different from the other normal & boringretreats',
//              '	Our company could apply such ideas for its employees because treating the employees is also an important aspect to note.This ideas are for its employees which will help to increase their engagement and this can add more to their dedication and commitment towards their work',
//              'CORPORATE PARTIES'),
//          tiles(
//              scaffoldState,
//              height,
//              width,
//              'Company Anniversary',
//              imageURLs[36],
//              '	The technology company continental celebrates 300 years of surface competence.Anniversary event: star guests and four days of events June 6-9, the factory grounds at Beneckeallee in Hanover.Visitors are invited to experience the fascination of the product in the facility, to submerge themselves into the world of materials, and to take a trip through time- from the first idea for a surface to innovationfor the future.“IDEAS BEYOND SURFACES” is the motto for 300 year anniversary',
//              'An anniversary year is an important milestone for a company. A great venue makes for an even more perfect celebration, so choosing a locale for our company’s anniversary party is an important piece of the party planning process. We can have a contest or quiz on company history or some other contest about industry knowledge and have exciting prizes. ',
//              'CORPORATE PARTIES'),
        ],
      ),
    );
  }
}
